### ISSUE TITLE
is this something wrong on the continuumIO/conda side?

### ISSUE THREAD

**Issue by johannct** [mjuric/conda-lsst#43] opened 2016-01-29 16:01 UTC
Hello, I tried to use the bootstrap script to install conda, but there seems to be something botched when conda tries to install additional packages : 
cohen@port-jct:~/lsst/dm/conda-lsst$ bash bin/bootstrap.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24.2M  100 24.2M    0     0  1233k      0  0:00:20  0:00:20 --:--:-- 1344k
PREFIX=/home/cohen/lsst/dm/conda-lsst/miniconda
installing: _cache-0.0-py27_x0 ...
installing: python-2.7.11-0 ...
installing: conda-env-2.4.5-py27_0 ...
installing: openssl-1.0.2d-0 ...
installing: pycosat-0.6.1-py27_0 ...
installing: pyyaml-3.11-py27_1 ...
installing: readline-6.2-2 ...
installing: requests-2.9.0-py27_0 ...
installing: sqlite-3.8.4.1-1 ...
installing: tk-8.5.18-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-0 ...
installing: conda-3.19.0-py27_0 ...
installing: pycrypto-2.6.1-py27_0 ...
installing: pip-7.1.2-py27_0 ...
installing: wheel-0.26.0-py27_1 ...
installing: setuptools-18.8.1-py27_0 ...
Python 2.7.11 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
Fetching package metadata: ....
Solving package specifications: ........................
Package plan for installation in environment /home/cohen/lsst/dm/conda-lsst/miniconda:

The following packages will be downloaded:

| package | build |
| --- | --- |
| openssl-1.0.2f | 0         3.2 MB |
| patchelf-0.8 | 0         258 KB |
| sqlite-3.9.2 | 0         3.9 MB |
| markupsafe-0.23 | py27_0          30 KB |
| requests-2.9.1 | py27_0         605 KB |
| setuptools-19.4 | py27_0         365 KB |
| sqlalchemy-1.0.11 | py27_0         1.3 MB |
| jinja2-2.8 | py27_0         263 KB |
| pip-8.0.1 | py27_0         1.5 MB |
| conda-build-1.18.2 | py27_0         207 KB |

```
------------------------------------------------------------
                                       Total:        11.6 MB
```

The following NEW packages will be INSTALLED:

```
conda-build: 1.18.2-py27_0
jinja2:      2.8-py27_0   
markupsafe:  0.23-py27_0  
patchelf:    0.8-0        
sqlalchemy:  1.0.11-py27_0
```

The following packages will be UPDATED:

```
openssl:     1.0.2d-0      --> 1.0.2f-0     
pip:         7.1.2-py27_0  --> 8.0.1-py27_0 
requests:    2.9.0-py27_0  --> 2.9.1-py27_0 
setuptools:  18.8.1-py27_0 --> 19.4-py27_0  
sqlite:      3.8.4.1-1     --> 3.9.2-0      
```

Fetching packages ...
Error: Could not open u'/home/cohen/lsst/dm/conda-lsst/miniconda/pkgs/openssl-1.0.2f-0.tar.bz2.part' for writing (seek).

I do not understand why it would want to open a file that seems to be a partial download.... But note that the file is there : 
cohen@port-jct:~/lsst/dm/conda-lsst$ ls /home/cohen/lsst/dm/conda-lsst/miniconda/pkgs/openssl-1.0.2*
/home/cohen/lsst/dm/conda-lsst/miniconda/pkgs/openssl-1.0.2f-0.tar.bz2.part

/home/cohen/lsst/dm/conda-lsst/miniconda/pkgs/openssl-1.0.2d-0:
bin  include  info  lib  ssl

any idea or a pointer to let conda folks know?

**Comment by jhoblitt** [comment] 2016-01-29 21:21
That is likely a local I/O error due to permissions or a full volume.

**Comment by mjuric** [comment] 2016-01-29 21:57
Yes, looks like you're out of space or over quota?

**Comment by johannct** [comment] 2016-01-30 06:13
weird.... I am on my laptop, and I still have plenty of space according to df. I removed 8GB for the sake of it, and the problem persists. I even copied the part file in place just to convince myself that I can add files in the same directory : 
Fetching packages ...
Error: Could not open u'/home/cohen/lsst/dm/conda-lsst/miniconda/pkgs/openssl-1.0.2f-0.tar.bz2.part' for writing (seek).
cohen@port-jct:~/lsst/dm/conda-lsst$ cp  /home/cohen/lsst/dm/conda-lsst/miniconda/pkgs/openssl-1.0.2f-0.tar.bz2.part /home/cohen/lsst/dm/conda-lsst/miniconda/pkgs/openssl-1.0.2f-0.tar.bz2.part2
cohen@port-jct:~/lsst/dm/conda-lsst$ cp  /home/cohen/lsst/dm/conda-lsst/miniconda/pkgs/openssl-1.0.2f-0.tar.bz2.part /home/cohen/lsst/dm/conda-lsst/miniconda/pkgs/openssl-1.0.2f-0.tar.bz2.part3
cohen@port-jct:~/lsst/dm/conda-lsst$ ls -ltr  /home/cohen/lsst/dm/conda-lsst/miniconda/pkgs/openssl-1.0.2f-0.tar.bz2.part*
-rw-rw-r-- 1 cohen cohen 16384 janv. 30 07:10 /home/cohen/lsst/dm/conda-lsst/miniconda/pkgs/openssl-1.0.2f-0.tar.bz2.part
-rw-rw-r-- 1 cohen cohen 16384 janv. 30 07:11 /home/cohen/lsst/dm/conda-lsst/miniconda/pkgs/openssl-1.0.2f-0.tar.bz2.part2
-rw-rw-r-- 1 cohen cohen 16384 janv. 30 07:11 /home/cohen/lsst/dm/conda-lsst/miniconda/pkgs/openssl-1.0.2f-0.tar.bz2.part3

no problem whatsoever.... still baffled.

**Comment by mjuric** [comment] 2016-02-01 03:51
What happens if you remove `openssl-1.0.2f-0.tar.bz2.part`?

Btw., this seems to be a `conda` problem -- googling uncovered:
- https://github.com/ContinuumIO/anaconda-issues/issues/416
- http://askubuntu.com/questions/564298/conda-update-package-permission-issues
- https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/G_gZ7x_8YV0
- https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/-pVlea20XR4
  etc..

I'll close this issue as it's not caused by our recipes -- could you follow up with the conda team on https://github.com/ContinuumIO/anaconda-issues/issues/416 ?

**Closed as completed by mjuric** 2016-02-01 03:51 UTC

**Comment by johannct** [comment] 2016-02-01 08:31
thanks for the pointer Mario!
